### ISSUE TITLE
Misleading error about includes

### ISSUE THREAD

**Issue by haack42** [seamia/protodot#11]
In a run I found this which was fixed once I downloaded the google apis and stored then in the includes list then it started working:

```
*** failed to find file [ google/api/annotations.proto ] with root [ /Users/...REMOVED... ]
*** failed to find file [ google/protobuf/struct.proto ] with root [ /Users/...REMOVED... ]
*** failed to find file [ google/protobuf/any.proto ] with root [ /Users/...REMOVED... ]
ASSERT: Unresolved type:  google.protobuf.Any ; source:  our.own.Dependency
```

The default config.json includes does not work, the folder `"${HOME}/protodot/protoc-3.6.0/include"` was not in that location, even not after running `protodot -install`. The `README.md` should be updated to give some instructions to put the base proto files there.

Built the executable from code on MacOS.

**Comment by omardelarosa** [comment]
I'm having the same issue. ☹️

**Comment by seamia** [comment]
**Hello** and **thank you** for your report.
Sounds like, you **got your issue resolved** based on the content of the error message.
Is this correct?
What part of the error message did you find misleading?

If you still experience any issues, repeated or new, please follow the following format what reporting them:
* what I **wanted**: ?
* what I **did**: ?
* what I **expected**: ?
* what I **got**: ?
* what I **propose**: ?
