### ISSUE TITLE
Default config should be search in protodot/config.json

### ISSUE THREAD

**Issue by haack42** [seamia/protodot#12]
There should be a default path list for the config present, such as in `config.hson` and if not found then `protodot/config.json`, etc. Specifying it each time does not make sense.

**Comment by seamia** [comment]
**Hello** and **thank you** for your report.

1. The config file name can be specified using CLI argument, e.g. "-config my.config". If it was not specified, the name "config.json" is used.
2. The logic of looking for location of the config file is:
3. Directory where the application is located (concatenated with provided or default config name)
4. Current Working directory (concatenated with provided or default config name)
5. If config file name is "config.json", and config file wasn't found using two aforementioned locations - an internal version of configuration settings is used.

Hopefully this provides enough information to get you moving.

If you still experience any issues, repeated or new, please follow the following format what reporting them:

* what I **wanted**: ?
* what I **did**: ?
* what I **expected**: ?
* what I **got**: ?
* what I **propose**: ?
