### ISSUE TITLE
Failed to load template file(s)

### ISSUE THREAD

**Issue by evenmun** [seamia/protodot#15]
After the last [change/commit](https://github.com/seamia/protodot/commit/e0d04ff29b382c7b9eaf5d35bdea112cdf754357), we get an error message that it cannot find the template files.

**Error msg for proto file 1:**
`failed to load templates file [templates/oneof_entry_suffix.tmpl] not found`

**Error msg for proto file 2:**
`failed to load templates file [templates/enum_suffix.tmpl] not found`

----------------------------------------------------------------------------------------------
**Command used:**
`protodot -config ../protodot.json -inc /usr/include -src *.proto -select AnyService -output AnyService`

**Comment by seamia** [comment]
Thank you very much for reporting this issue.
As of now, I was addressed (fixed).
Please, either:
* get the latest prebuilt binaries, or
* pull the latest sources and rebuild (v1.2.0)

Thank you again!
