### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by navaneeth-spotnana** [seamia/protodot#2]
https://protodot.seamia.net/ is down, when I tried to download this "looking some awesome" project. Can you bring it up?

**Comment by seamia** [comment]
hmm, seems to be ON now

**Comment by gowtham1997** [comment]
Looks like it's down again, cant download the binary file to run the code

**Comment by navaneeth-spotnana** [comment]
Might be India specific, but the site was down every time I checked spanning last 2 months.

**Comment by seamia** [comment]
FYI: I added an alternative location for the pre-built binaries:
https://github.com/seamia/protodot/tree/master/binaries
