### ISSUE TITLE
Add comments from the .proto files to the output graph

### ISSUE THREAD

**Issue by ShayNehmad-RecoLabs** [seamia/protodot#4]
Hi!
It would be super-useful for me if comments I leave above fields in protobuf will carry over to the .dot (and .svg) file. Any way to make this happen? Would love to help with guidance

**Comment by seamia** [comment]
**Hello** and **thank you** for your report.

Unfortunately, there is no good way (that we can see) to render potentially large swaths of comments that a *.proto file can contain.
We will keep this feature in the backlog of things to do.
