### ISSUE TITLE
How to add a target path for output file?

### ISSUE THREAD

**Issue by ironsuperdev** [seamia/protodot#7]
Hello, I tried with -output option with "home/put/it/here/target", but I got an error.

How to do this?  Thanks!

**Comment by seamia** [comment]
**step 1:**
run `protodot -install`
this will, besides other things, create a copy of config file `config.json`

**step 2:**
make a copy of `config.json`, e.g. `ironsuperdev.json`

**step 3:**
within your config file (`ironsuperdev.json`) enter desired location of generated files (under "locations" and "generated")

**step 4:**
run `protodot` as before, but add the following parameters:
`-config ironsuperdev.json`
